defaults:
  # default backend is pytorch
  - backend: pytorch
  # default benchmark is inference
  - benchmark: inference
  # other parameters are infered from:
  - experiment # dataclass (contains environment state)
  - _self_ # for hydra 1.1 compatibility
  # use colorlog for logging (colorful output)
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: runs/${experiment_name}
  sweep:
    dir: sweeps/${experiment_name}
  job:
    # enables changing the working directory to the run/sweep directory
    chdir: true

model: ??? # model is mandatory
device: ??? # device to run on is mandatory
task: ${infer_task:${model}} # task is infered from model

# a distinct experiment name should be used for each experiment
experiment_name: ??? # experiment name is mandatory
